const actions = {
  STAND: "stand",
  WALK: "walking",
  WALK_BACKWARD: "walking-backward",
  SQUAT: "squating",
  HIGH_KICK: "high-kick",
  JUMP: "jumping",
  FORWARD_JUMP: "forward-jump",
  BACKWARD_JUMP: "backward-jump",
  LOW_KICK: "low-kick",
  LOW_PUNCH: "low-punch",
  HIGH_PUNCH: "high-punch",
  UPPERCUT: "uppercut",
  SQUAT_LOW_KICK: "squat-low-kick",
  SQUAT_HIGH_KICK: "squat-high-kick",
  SQUAT_LOW_PUNCH: "squat-low-punch",
  SPIN_KICK: "spin-kick",
  BLOCK: "blocking",
};
