const actions = {
  STAND: "stand",
  WALK: "walking",
  WALK_BACKWARD: "walking-backward",
  SQUAT: "squating",
  STAND_UP: "stand-up",
  HIGH_KICK: "high-kick",
  JUMP: "jumping",
  FORWARD_JUMP: "forward-jump",
  BACKWARD_JUMP: "backward-jump",
  LOW_KICK: "low-kick",
  LOW_PUNCH: "low-punch",
  HIGH_PUNCH: "high-punch",
  UPPERCUT: "uppercut",
  SQUAT_LOW_KICK: "squat-low-kick",
  SQUAT_HIGH_KICK: "squat-high-kick",
  SQUAT_LOW_PUNCH: "squat-low-punch",
  KNOCK_DOWN: "knock-down",
  ATTRACTIVE_STAND_UP: "attractive-stand-up",
  SPIN_KICK: "spin-kick",
  BLOCK: "blocking",
  FORWARD_JUMP_KICK: "forward-jump-kick",
  BACKWARD_JUMP_KICK: "backward-jump-kick",
  BACKWARD_JUMP_PUNCH: "backward-jump-punch",
  FORWARD_JUMP_PUNCH: "forward-jump-punch",
};
