const rewards = {
  stand: 0,
  walking: 0,
  "walking-backward": 0,
  squating: 0,
  "high-kick": 0,
  jumping: 0,
  "forward-jump": 20,
  "backward-jump": 20,
  "low-kick": 0,
  "low-punch": 0,
  "high-punch": 0,
  uppercut: 40,
  "squat-low-kick": 20,
  "squat-high-kick": 20,
  "squat-low-punch": 20,
  "spin-kick": 35,
  blocking: 0,
};
