const rewards = {
  stand: 0,
  walking: 0,
  "walking-backward": 0,
  squating: 10,
  "high-kick": 0,
  jumping: 0,
  "forward-jump": 5,
  "backward-jump": 5,
  "low-kick": 0,
  "low-punch": 0,
  "high-punch": 0,
  uppercut: 20,
  "squat-low-kick": 5,
  "squat-high-kick": 5,
  "squat-low-punch": 5,
  "spin-kick": 35,
  blocking: 5,
};
